language: ruby
cache: bundler
rvm:
- 2.3.0
script:
- bundle exec jekyll --version
- ls -lah
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: AKIAIH6ZAE5UVSWXTBHA
  secret_access_key:
    secure: g3F0bdS2KrhwNbVrcxU7Hh7/3V0m4+fJ0U9oAgurlxMYEw6LDx2vctOThv3GELtk2N1miX8KWVPBDKnuoLBcqLrDHs28zl3QNu4/EBt9SvI2ezd5eQ+cBm+lwlsVO5yeE4nctFn+R/SfFtoVlUqFeIHVvdMVWwyrBzpfNsDCSR3A7Il0y5DLPDYEZZdem1oxwOJvIuzHGEs2mWb1gyMEtI/AwzZRhjx0ddVP+2oWt3KH+zFPyyqnyghnsmbyZsPZdqE5umU5r4kaUkdRiglmUZuJQnjarW23bQUyVpUz66Lj6lzl53/XPrCgxz4uv55hWZIEQC5j44MOUsHbtYzaa9tRWS9wcIiusuUjlltZ01ioGt9CdGTydektiWWR8YxvdHbld1lax64Rn1p0DQN6AhpQ0un3GU5k+3E/WC24pGu9lIRoJKg/ka7dWUl+k2jmEvqZ1SjWunuIkWfzeDIUi9y7eITusiZGLrjipoCmhgAuqnC5Qcl2XS/5wnxWIs+5myoXuzK49Rr09cA1AgxHQ9HjaK4q5gWXiE0Wi6ZRj5s3d9Uv8dCEDvpirTl1/atm84eSmuP8dXHdqTt4+iyC6+vyWn5hoeE2grrL+W36PpheQ19eHomfAr7muOf1Z4wRFmiDlNnSd9fFN8Qw6CFUBzGc4A4HgilulzKj4YfEwPk=
  bucket: vvv.org
  skip_cleanup: true
  acl: public_read
  region: us-west-2
  local_dir: _site
  detect_encoding: true
  default_text_charset: 'utf-8'
  on:
    branch: master
